version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: postgresql://user:password@postgres:5432/weatherdb

volumes:
  pgdata: